openapi: 3.2.0
info:
  title: Счета и документы Bills API
  description: Управление счетами на оплату и закрывающими документами
  version: 1.0.0
servers:
- url: https://api.raiffeisen.ru/invoices
tags:
- name: Bills
  description: Управление выставлением счетов на оплату
paths:
  /v4/bills/{billId}:
    get:
      tags:
      - Bills
      summary: Получить детальную информацию о счете на оплату
      description: Возвращает детальную информацию о счете на оплату по id
      operationId: getBillDetails
      parameters:
      - name: billId
        in: path
        required: true
        description: Идентификатор счета на оплату
        schema:
          type: string
          format: uuid
          example: 60612e6c-d182-4b59-a868-69714a910ee3
      - $ref: '#/components/parameters/AuthorizationHeader'
      - $ref: '#/components/parameters/IdTokenHeader'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BillDetailsResponse'
              examples:
                billDetailsResponse:
                  $ref: '#/components/examples/billDetailsResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalError'
    put:
      tags:
      - Bills
      summary: Обновить счет на оплату
      description: Обновляет информацию о счете на оплату по id
      operationId: updateBill
      parameters:
      - name: billId
        in: path
        required: true
        description: Идентификатор счета на оплату
        schema:
          type: string
          format: uuid
          example: 60612e6c-d182-4b59-a868-69714a910ee3
      - $ref: '#/components/parameters/AuthorizationHeader'
      - $ref: '#/components/parameters/IdTokenHeader'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BillUpdateRequest'
            examples:
              billUpdateRequest:
                $ref: '#/components/examples/billUpdateRequest'
        required: true
      responses:
        '204':
          description: OK
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalError'
  /v4/bills/status:
    put:
      tags:
      - Bills
      summary: Обновить статус счетов
      description: Обновить статус одного или нескольких счетов по списку id
      operationId: deleteBills
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BillStatusUpdateRequest'
            examples:
              billStatusUpdateRequest:
                $ref: '#/components/examples/billStatusUpdateRequest'
        required: true
      responses:
        '204':
          description: OK
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalError'
      parameters:
      - $ref: '#/components/parameters/AuthorizationHeader'
      - $ref: '#/components/parameters/IdTokenHeader'
  /v4/bills:
    get:
      tags:
      - Bills
      summary: Получить список счетов на оплату
      description: Возвращает список счетов на оплату с возможностью фильтрации
      operationId: getBillList
      parameters:
      - name: page
        in: query
        required: false
        description: Номер страницы для пагинации, нумерация с нуля
        schema:
          type: integer
          format: int32
          default: 0
          minimum: 0
          example: 0
      - name: size
        in: query
        required: false
        description: Количество элементов на странице
        schema:
          type: integer
          format: int32
          default: 30
          maximum: 50
          minimum: 1
          example: 30
      - name: statuses
        in: query
        required: false
        description: Список статусов счетов для фильтрации
        schema:
          type: array
          items:
            type: string
            description: Статус счета на оплату
            enum:
            - PAYMENT_PENDING
            - PAID
            example: PAYMENT_PENDING
          uniqueItems: true
          example:
          - PAYMENT_PENDING
      - name: year
        in: query
        required: false
        description: Год выставления счета для фильтрации
        schema:
          type: integer
          format: int32
          minimum: 1
          example: 2026
      - name: date
        in: query
        required: false
        description: Дата выставления счета для точной фильтрации
        schema:
          type: string
          format: date
          example: '2026-09-30'
      - name: periodFrom
        in: query
        required: false
        description: Начало периода фильтрации по дате выставления счета (включительно)
        schema:
          type: string
          format: date
          example: '2026-09-01'
      - name: periodTo
        in: query
        required: false
        description: Конец периода фильтрации по дате выставления счета (включительно)
        schema:
          type: string
          format: date
          example: '2026-09-30'
      - name: sumFrom
        in: query
        required: false
        description: Минимальная сумма счета (включительно) для фильтрации
        schema:
          type: number
          example: 1000.0
      - name: sumTo
        in: query
        required: false
        description: Максимальная сумма счета (включительно) для фильтрации
        schema:
          type: number
          example: 500000.0
      - name: customerSearchString
        in: query
        required: false
        description: Строка поиска по ИНН плательщика
        schema:
          type: string
          example: '394439302723'
      - name: query
        in: query
        required: false
        description: Строка полнотекстового поиска по счету (наименование, номер, контрагент)
        schema:
          type: string
          example: Услуги по настройке ПО
      - $ref: '#/components/parameters/AuthorizationHeader'
      - $ref: '#/components/parameters/IdTokenHeader'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PageBillMiniResponse'
              examples:
                billListResponse:
                  $ref: '#/components/examples/billListResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalError'
    post:
      tags:
      - Bills
      summary: Сформировать счет на оплату
      description: Сохраняет новый счет на оплату
      operationId: saveBill
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BillRequest'
            examples:
              billRequest:
                $ref: '#/components/examples/billRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BillResponse'
              examples:
                billResponse:
                  $ref: '#/components/examples/billResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalError'
      parameters:
      - $ref: '#/components/parameters/AuthorizationHeader'
      - $ref: '#/components/parameters/IdTokenHeader'
    delete:
      tags:
      - Bills
      summary: Удалить счета на оплату
      description: Удалить один или несколько счетов на оплату по списку id
      operationId: markBillsRemoved
      parameters:
      - name: ids
        in: query
        required: true
        description: Список идентификаторов счетов на оплату для удаления
        schema:
          type: array
          items:
            type: string
            format: uuid
            example: 3fa85f64-5717-4562-b3fc-2c963f66afa6
          example:
          - 3fa85f64-5717-4562-b3fc-2c963f66afa6
      - $ref: '#/components/parameters/AuthorizationHeader'
      - $ref: '#/components/parameters/IdTokenHeader'
      responses:
        '204':
          description: OK
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalError'
  /v4/bills/{billId}/document:
    get:
      tags:
      - Bills
      summary: Получить счет на оплату в виде документа
      description: Возвращает счет на оплату в виде документа (XML или PDF) по его id. Для PDF можно запросить вариант без информации о формировании документа (параметр withoutGenerationInfo)
      operationId: getDocument
      parameters:
      - name: billId
        in: path
        required: true
        description: Идентификатор счета на оплату
        schema:
          type: string
          format: uuid
          example: 60612e6c-d182-4b59-a868-69714a910ee3
      - name: docType
        in: query
        required: false
        description: Формат файла документа
        schema:
          type: string
          enum:
          - PDF
          - XML
          example: PDF
      - name: withoutGenerationInfo
        in: query
        required: false
        description: Исключить из PDF блок с информацией о формировании документа
        schema:
          type: boolean
          default: false
          example: false
      - $ref: '#/components/parameters/AuthorizationHeader'
      - $ref: '#/components/parameters/IdTokenHeader'
      responses:
        '200':
          description: OK
          content:
            application/xml;charset=windows-1251:
              schema:
                type: string
                format: byte
            application/pdf:
              schema:
                type: string
                format: byte
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalError'
  /v4/bills/measurements:
    get:
      tags:
      - Bills
      summary: Получить список единиц измерения
      description: Возвращает список единиц измерения, которые можно использовать при сохранении счета на оплату
      operationId: getMeasurements
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MeasurementResponse'
              examples:
                measurementResponse:
                  $ref: '#/components/examples/measurementResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalError'
      parameters:
      - $ref: '#/components/parameters/AuthorizationHeader'
      - $ref: '#/components/parameters/IdTokenHeader'
  /v4/bills/doc-number/next:
    get:
      tags:
      - Bills
      summary: Получение следующего свободного номера документа для счета на оплату
      description: Возвращает свободный номер документа, который можно использовать при сохранении нового счета на оплату
      operationId: getNextDocNumber
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocNumberResponse'
              examples:
                docNumberResponse:
                  value:
                    nextDocNumber: '12'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalError'
      parameters:
      - $ref: '#/components/parameters/AuthorizationHeader'
      - $ref: '#/components/parameters/IdTokenHeader'
components:
  schemas:
    BillUpdateRequest:
      type: object
      description: Корневая модель обновления документа
      properties:
        goods:
          $ref: '#/components/schemas/GoodsUpdateRequest'
          description: Модель с товарами
        invoice:
          $ref: '#/components/schemas/Invoice'
          description: Модель выставленного счёта
        payer:
          $ref: '#/components/schemas/PayerRequest'
          description: Модель с данными плательщика
        payee:
          $ref: '#/components/schemas/PayeeRequest'
          description: Модель с данными получателя
        closingDocuments:
          type: array
          description: Связанные со счетом закрывающие документы
          items:
            type: string
            format: uuid
          uniqueItems: true
          example:
          - 3fa85f64-5717-4562-b3fc-2c963f66afa6
      required:
      - goods
      - invoice
      - payee
      - payer
    BillDetailsResponse:
      type: object
      description: Детальная информация о счете на оплату
      properties:
        id:
          type: string
          format: uuid
          description: Идентификатор счета
          example: 60612e6c-d182-4b59-a868-69714a910ee3
        status:
          type: string
          description: Статус счета на оплату
          enum:
          - PAYMENT_PENDING
          - PAID
          example: PAYMENT_PENDING
        docNumber:
          type: string
          description: Номер документа
          example: '1'
        cnum:
          type: string
          description: CNUM организации
          example: UVGASK
        goods:
          $ref: '#/components/schemas/GoodsResponse'
        invoice:
          $ref: '#/components/schemas/Invoice'
          description: Счёт на оплату
        payer:
          $ref: '#/components/schemas/Payer'
          description: Плательщик
        payee:
          $ref: '#/components/schemas/PayeeResponse'
          description: Получатель платежа
        linkedDocuments:
          type: array
          description: Связанные закрывающие документы
          items:
            $ref: '#/components/schemas/BillDetailsLinkedDocumentResponse'
          example:
          - id: 60612e6c-d182-4b59-a868-69714a910ee3
            type: WORK_ACT
            documentNumber: '35503799'
            documentDate: '2026-09-30'
            totalPrice: 22600.0
            totalVatAmount: 0.0
        payments:
          type: array
          description: Оплаты по счету
          items:
            $ref: '#/components/schemas/BillPaymentResponse'
          example:
          - transactionKey: 2026-09-30_401900899873_123_6002.50
            operDate: '2026-09-30'
            total: 6002.5
        statusIsUpdating:
          type: boolean
          description: Признак того, что статус счета сейчас обновляется
          example: false
        createdOn:
          type: string
          format: date-time
          description: Дата и время создания счета
          example: '2026-09-30T10:19:26Z'
        receipts:
          type: array
          description: Связанные чеки самозанятых
          items:
            type: string
            format: uuid
          example:
          - 3fa85f64-5717-4562-b3fc-2c963f66afa6
      required:
      - cnum
      - createdOn
      - docNumber
      - goods
      - id
      - invoice
      - linkedDocuments
      - payee
      - payer
      - payments
      - receipts
      - status
      - statusIsUpdating
    BillResponse:
      type: object
      description: Корневая модель исходящего документа.
      properties:
        documentId:
          type: string
          format: uuid
          description: Идентификатор сохранённого документа.
          example: 3fa85f64-5717-4562-b3fc-2c963f66afa6
      required:
      - documentId
    AccountRequest:
      type: object
      description: Счёт получателя
      example:
        name: АО «Банк»
        num: '51421810026450470886'
        bic: 081395980
        corrAcc: '30101810400000000598'
      properties:
        name:
          type: string
          description: Наименование счёта
          example: АО «Банк»
        num:
          type: string
          description: Номер счёта
          example: '51421810026450470886'
        bic:
          type: string
          description: БИК получателя
          example: 081395980
        branchName:
          type: string
          description: Наименование отделения банка получателя
          example: Московский филиал АО «Банк»
        corrAcc:
          type: string
          description: Корреспондентский счёт
          example: '30101810400000000598'
      required:
      - bic
      - name
      - num
    Sort:
      type: object
      description: Информация о сортировке
      example:
        sorted: true
        unsorted: false
        empty: false
      properties:
        sorted:
          type: boolean
          description: Признак отсортированного результата
          example: true
        unsorted:
          type: boolean
          description: Признак неотсортированного результата
          example: false
        empty:
          type: boolean
          description: Признак отсутствия сортировки
          example: false
    PageBillMiniResponse:
      type: object
      description: Страница со списком счетов на оплату
      properties:
        totalElements:
          type: integer
          format: int64
          description: Всего элементов
          example: 40
        totalPages:
          type: integer
          format: int32
          description: Всего страниц
          example: 2
        first:
          type: boolean
          description: Признак первой страницы
          example: true
        last:
          type: boolean
          description: Признак последней страницы
          example: false
        statusIsUpdating:
          type: boolean
          description: Признак того, что статусы счетов сейчас обновляются
          example: false
        numberOfElements:
          type: integer
          format: int32
          description: Количество элементов на текущей странице
          example: 30
        pageable:
          $ref: '#/components/schemas/Pageable'
          description: Информация о пагинации
        size:
          type: integer
          format: int32
          description: Размер страницы
          example: 30
        content:
          type: array
          description: Список счетов на оплату
          items:
            $ref: '#/components/schemas/BillMiniResponse'
          example:
          - id: 60612e6c-d182-4b59-a868-69714a910ee3
            cnum: UVGASK
            status: PAYMENT_PENDING
            createdDate: 1.790763566E9
            invoiceDate: 1.7907264E9
            docNumber: '1'
            amount: 6002.5
            items: []
            linkedDocuments: []
            numberOfRemainingLinkedDocuments: 0
            receipts: []
        number:
          type: integer
          format: int32
          description: Номер текущей страницы
          example: 0
        sort:
          $ref: '#/components/schemas/Sort'
          description: Информация о сортировке
        empty:
          type: boolean
          description: Признак пустой страницы
          example: false
    CDListLinkedDocumentResponse:
      type: object
      description: Список связанных документов
      properties:
        id:
          type: string
          format: uuid
          description: Идентификатор связанного документа
          example: 60612e6c-d182-4b59-a868-69714a910ee3
        type:
          type: string
          description: Тип связанного документа. Одно из значений BILL, WORK_ACT, CONSIGNMENT_NOTE, INVOICE_FACTURA
          example: BILL
        documentNumber:
          type: string
          description: Номер связанного документа
          example: '1'
      required:
      - id
      - type
    PayeeMiniResponse:
      type: object
      description: Получатель платежа
      properties:
        name:
          type: string
          description: Наименование получателя платежа
          example: ООО Продавец
        inn:
          type: string
          description: ИНН получателя платежа
          example: '394439302723'
        kpp:
          type: string
          description: КПП получателя платежа
          example: '637996731'
        address:
          type: string
          description: Адрес получателя платежа
          example: 123154, Москва г, ул. Тестовая, д. 2
    ItemMiniResponse:
      type: object
      description: Модель товара
      properties:
        id:
          type: string
          format: uuid
          description: Идентификатор товара (возвращается в ответах по счетам, у закрывающих документов отсутствует)
          example: 7c9e6679-7425-40de-944b-e07fc1f90ae7
        name:
          type: string
          description: Наименование единицы товара.
          example: Услуги по настройке ПО
        count:
          type: number
          description: Количество
          example: 5
        price:
          type: number
          description: Цена единицы товара
          example: 1200.5
        vat:
          $ref: '#/components/schemas/Unit'
          description: НДС
        unit:
          $ref: '#/components/schemas/Unit'
          description: Единица измерения
        sum:
          type: number
          description: Итоговая стоимость
          example: 6002.5
        vatAmount:
          type: number
          description: НДС
          example: 1000.42
      required:
      - count
      - name
      - price
      - sum
      - unit
      - vat
      - vatAmount
    BillDetailsLinkedDocumentResponse:
      type: object
      description: Связанный документ в детальной информации о счете
      properties:
        id:
          type: string
          format: uuid
          description: Идентификатор связанного документа
          example: 60612e6c-d182-4b59-a868-69714a910ee3
        type:
          type: string
          description: Тип закрывающего документа
          enum:
          - BILL
          - WORK_ACT
          - CONSIGNMENT_NOTE
          - UPD
          - INVOICE_FACTURA
          example: WORK_ACT
        documentNumber:
          type: string
          description: Номер связанного документа
          example: '35503799'
        documentDate:
          type: string
          format: date
          description: Дата связанного документа
          example: '2026-09-30'
        totalPrice:
          type: number
          description: Итоговая сумма
          example: 22600.0
        totalVatAmount:
          type: number
          description: Итоговый НДС
          example: 0.0
        payer:
          $ref: '#/components/schemas/Payer'
          description: Плательщик
      required:
      - documentDate
      - id
      - totalPrice
      - totalVatAmount
      - type
    ItemUpdateRequest:
      type: object
      description: Модель единицы товара
      example:
        id: 3fa85f64-5717-4562-b3fc-2c963f66afa6
        name: Услуги по настройке ПО
        count: 5
        price: 1200.5
        unit: HOUR
        vat: VAT_20
      properties:
        id:
          type: string
          format: uuid
          description: Идентификатор товара
          example: 3fa85f64-5717-4562-b3fc-2c963f66afa6
        name:
          type: string
          description: Наименование единицы товара
          example: Услуги по настройке ПО
        count:
          type: number
          description: Количество
          example: 5
        price:
          type: number
          description: Цена единицы товара
          example: 1200.5
        unit:
          type: string
          description: Единица измерения товара
          example: HOUR
          enum:
          - PIECE
          - MINUTE
          - HOUR
          - DAY
          - CENTIMETER
          - DECIMETER
          - METER
          - KILOMETER
          - SQUARE_METER
          - HECTARE
          - CUBIC_METER
          - LITER
          - GRAM
          - KILOGRAM
          - TON
          - KIT
          - BOX
          - KILOWATT_HOUR
          - GIGA_CALORIES
          - STANDARD_UNIT
          - LINEAR_METER
          - PACKAGE
          - SERVICE
          - PAIR
          - MACHINE_HOUR
          - MONTH
          - EMPTY
        vat:
          type: string
          description: НДС.
          example: VAT_20
          enum:
          - VAT_0
          - NO_VAT
          - VAT_22
          - VAT_20
          - VAT_18
          - VAT_10
          - VAT_7
          - VAT_5
      required:
      - count
      - name
      - price
      - unit
      - vat
    Unit:
      type: object
      description: Модель единицы измерения
      properties:
        name:
          type: string
          description: Кодовое название
          example: PIECE
        abbreviation:
          type: string
          description: Единица измерения
          example: Штуки
        value:
          type: string
          description: Значение
          example: шт
      required:
      - abbreviation
      - name
      - value
    PayerMiniResponse:
      type: object
      description: Плательщик
      properties:
        name:
          type: string
          description: Наименование плательщика
          example: ООО Покупатель
        type:
          type: string
          description: Тип плательщика. INDIVIDUAL (ФЛ) / LEGAL (юр. лицо) / NONE (без типа)
          enum:
          - INDIVIDUAL
          - LEGAL
          - NONE
          example: LEGAL
        inn:
          type: string
          description: ИНН плательщика
          example: '394439302723'
        kpp:
          type: string
          description: КПП плательщика
          example: '637996731'
        address:
          type: string
          description: Адрес плательщика
          example: г. Москва, ул. Тестовая, д. 1
    Pageable:
      type: object
      description: Информация о пагинации
      example:
        paged: true
        pageNumber: 0
        pageSize: 30
        unpaged: false
        offset: 0
        sort:
          sorted: true
          unsorted: false
          empty: false
      properties:
        paged:
          type: boolean
          description: Признак постраничного вывода
          example: true
        pageNumber:
          type: integer
          format: int32
          description: Номер страницы
          example: 0
        pageSize:
          type: integer
          format: int32
          description: Размер страницы
          example: 30
        unpaged:
          type: boolean
          description: Признак непостраничного вывода
          example: false
        offset:
          type: integer
          format: int64
          description: Смещение от начала выборки
          example: 0
        sort:
          $ref: '#/components/schemas/Sort'
          description: Информация о сортировке
    BillMiniResponse:
      type: object
      description: Краткая информация о счете на оплату
      properties:
        id:
          type: string
          format: uuid
          description: Идентификатор счета
          example: 60612e6c-d182-4b59-a868-69714a910ee3
        cnum:
          type: string
          description: CNUM организации
          example: UVGASK
        status:
          type: string
          description: Статус счета на оплату
          enum:
          - PAYMENT_PENDING
          - PAID
          example: PAYMENT_PENDING
        createdDate:
          type: number
          description: Дата и время создания счета (количество секунд с начала эпохи Unix, десятичная дробь с наносекундами)
          example: 1.790763566E9
        invoiceDate:
          type: number
          description: Дата выставления счета (количество секунд с начала эпохи Unix, десятичная дробь с наносекундами)
          example: 1.7907264E9
        docNumber:
          type: string
          description: Номер документа
          example: '1'
        payer:
          $ref: '#/components/schemas/PayerMiniResponse'
          description: Плательщик
        payee:
          $ref: '#/components/schemas/PayeeMiniResponse'
          description: Получатель платежа
        amount:
          type: number
          description: Сумма счета
          example: 6002.5
        items:
          type: array
          description: Список товаров
          items:
            $ref: '#/components/schemas/ItemMiniResponse'
        linkedDocuments:
          type: array
          description: Связанные закрывающие документы
          items:
            $ref: '#/components/schemas/CDListLinkedDocumentResponse'
        numberOfRemainingLinkedDocuments:
          type: integer
          format: int32
          description: Количество связанных документов, которые не вернулись в ответе
          example: 0
        receipts:
          type: array
          description: Связанные чеки самозанятых
          items:
            type: string
            format: uuid
          example:
          - 3fa85f64-5717-4562-b3fc-2c963f66afa6
      required:
      - amount
      - cnum
      - createdDate
      - docNumber
      - id
      - invoiceDate
      - items
      - linkedDocuments
      - numberOfRemainingLinkedDocuments
      - payee
      - payer
      - receipts
      - status
    BillRequest:
      type: object
      description: Корневая модель входящего документа
      properties:
        goods:
          $ref: '#/components/schemas/GoodsRequest'
          description: Модель с товарами
        invoice:
          $ref: '#/components/schemas/Invoice'
          description: Модель выставленного счёта
        payer:
          $ref: '#/components/schemas/PayerRequest'
          description: Модель с данными плательщика
        payee:
          $ref: '#/components/schemas/PayeeRequest'
          description: Модель с данными получателя
        closingDocuments:
          type: array
          description: Связанные со счетом закрывающие документы
          items:
            type: string
            format: uuid
          uniqueItems: true
          example:
          - 3fa85f64-5717-4562-b3fc-2c963f66afa6
        receipts:
          type: array
          description: Связанные со счетом чеки самозанятых
          items:
            type: string
            format: uuid
          uniqueItems: true
          example:
          - 3fa85f64-5717-4562-b3fc-2c963f66afa6
      required:
      - goods
      - invoice
      - payee
      - payer
    MeasurementResponse:
      type: object
      description: Модель списка единиц измерения
      properties:
        vat:
          type: array
          description: Список НДС.
          items:
            $ref: '#/components/schemas/Unit'
          example:
          - name: VAT_0
            abbreviation: НДС 0%
            value: '0'
        units:
          type: array
          description: Единицы измерения.
          items:
            $ref: '#/components/schemas/Unit'
          example:
          - name: PIECE
            abbreviation: Штуки
            value: шт
      required:
      - units
      - vat
    BillStatusUpdateRequest:
      type: object
      description: Запрос на обновление статуса счетов
      properties:
        billIds:
          type: array
          description: Список идентификаторов счетов для обновления статуса
          items:
            type: string
            format: uuid
          minItems: 1
          example:
          - 3fa85f64-5717-4562-b3fc-2c963f66afa6
        status:
          type: string
          description: Новый статус для счетов
          enum:
          - PAYMENT_PENDING
          - PAID
          example: PAID
      required:
      - billIds
      - status
    GoodsUpdateRequest:
      type: object
      description: DTO Информация о товарах
      example:
        items:
        - id: 3fa85f64-5717-4562-b3fc-2c963f66afa6
          name: Услуги по настройке ПО
          count: 5
          price: 1200.5
          unit: HOUR
          vat: VAT_20
      properties:
        items:
          type: array
          description: Товары
          example:
          - id: 3fa85f64-5717-4562-b3fc-2c963f66afa6
            name: Услуги по настройке ПО
            count: 5
            price: 1200.5
            unit: HOUR
            vat: VAT_20
          items:
            $ref: '#/components/schemas/ItemUpdateRequest'
      required:
      - items
    PayeeRequest:
      type: object
      description: Модель получателя платежа.
      example:
        inn: '394439302723'
        kpp: '637996731'
        name: ООО Продавец
        lawType: ООО
        juridicalAddress: 123154, Москва г, ул. Тестовая, д. 2
        account:
          name: АО «Банк»
          num: '51421810026450470886'
          bic: 081395980
          corrAcc: '30101810400000000598'
      properties:
        inn:
          type: string
          description: ИНН получателя платежа
          example: '394439302723'
        kpp:
          type: string
          description: КПП получателя платежа
          example: '637996731'
        name:
          type: string
          description: Наименование получателя платежа
          example: ООО Продавец
        lawType:
          type: string
          description: Организационно-правовая форма
          example: ООО
        juridicalAddress:
          type: string
          description: Юридический адрес получателя платежа
          example: 123154, Москва г, ул. Тестовая, д. 2
        account:
          $ref: '#/components/schemas/AccountRequest'
          description: Банковский счёт получателя платежа.
      required:
      - account
      - inn
      - juridicalAddress
    Invoice:
      type: object
      description: Счёт на оплату
      example:
        num: INV-2024-001
        date: '2026-09-30'
        cause: Оплата по договору №123456
        comment: Платёж по договору №123456
      properties:
        num:
          type: string
          description: Номер счёта в буквенно-цифровом формате (может содержать латиницу, кириллицу, цифры, дефис и слэш)
          example: INV-2024-001
          pattern: ^(?=[A-Za-zА-Яа-я0-9/-]{1,30})(?=.*[1-9]+).*$
        date:
          type: string
          format: date
          description: Дата выставления счёта
          example: '2007-12-03'
        cause:
          type: string
          description: Основание для выставления счёта
          example: Оплата по договору №123456
        comment:
          type: string
          description: Комментарий
          example: Платёж по договору №123456
      required:
      - date
      - num
    GoodsResponse:
      type: object
      description: Товары
      example:
        totalPrice: 6002.5
        totalVatAmount: 1000.42
        items:
        - name: Услуги по настройке ПО
          count: 5
          price: 1200.5
          vat:
            name: VAT_20
            abbreviation: НДС 20%
            value: '20'
          unit:
            name: HOUR
            abbreviation: Часы
            value: ч
          sum: 6002.5
          vatAmount: 1000.42
      properties:
        totalVatAmount:
          type: number
          description: Итоговый НДС
          example: 1000.42
        totalPrice:
          type: number
          description: Итоговая сумма
          example: 6002.5
        items:
          type: array
          description: Товары
          example:
          - name: Услуги по настройке ПО
            count: 5
            price: 1200.5
            vat:
              name: VAT_20
              abbreviation: НДС 20%
              value: '20'
            unit:
              name: HOUR
              abbreviation: Часы
              value: ч
            sum: 6002.5
            vatAmount: 1000.42
          items:
            $ref: '#/components/schemas/ItemMiniResponse'
      required:
      - items
      - totalPrice
      - totalVatAmount
    AccountResponse:
      type: object
      description: Банковский счёт получателя
      example:
        name: АО «Банк»
        num: '51421810026450470886'
        branchName: Московский филиал АО «Банк»
        corrAcc: '30101810400000000598'
        bic: 081395980
      properties:
        name:
          type: string
          description: Наименование банка
          example: АО «Банк»
        num:
          type: string
          description: Номер счёта
          example: '51421810026450470886'
        branchName:
          type: string
          description: Наименование отделения банка
          example: Московский филиал АО «Банк»
        corrAcc:
          type: string
          description: Корреспондентский счёт
          example: '30101810400000000598'
        bic:
          type: string
          description: БИК банка
          example: 081395980
      required:
      - bic
      - branchName
      - corrAcc
      - name
      - num
    ItemRequest:
      type: object
      description: Модель единицы товара
      properties:
        name:
          type: string
          description: Наименование единицы товара
          example: Услуги по настройке ПО
        count:
          type: number
          description: Количество
          example: 5
        price:
          type: number
          description: Цена единицы товара
          example: 1200.5
        unit:
          type: string
          description: Единица измерения товара
          example: HOUR
          enum:
          - PIECE
          - MINUTE
          - HOUR
          - DAY
          - CENTIMETER
          - DECIMETER
          - METER
          - KILOMETER
          - SQUARE_METER
          - HECTARE
          - CUBIC_METER
          - LITER
          - GRAM
          - KILOGRAM
          - TON
          - KIT
          - BOX
          - KILOWATT_HOUR
          - GIGA_CALORIES
          - STANDARD_UNIT
          - LINEAR_METER
          - PACKAGE
          - SERVICE
          - PAIR
          - MACHINE_HOUR
          - MONTH
          - EMPTY
        vat:
          type: string
          description: НДС
          example: VAT_20
          enum:
          - VAT_0
          - NO_VAT
          - VAT_22
          - VAT_20
          - VAT_18
          - VAT_10
          - VAT_7
          - VAT_5
      required:
      - count
      - name
      - price
      - unit
      - vat
    PayerRequest:
      type: object
      description: Модель плательщика
      example:
        type: LEGAL
        name: ООО Покупатель
        inn: '394439302723'
        kpp: '637996731'
        address: г. Москва, ул. Тестовая, д. 1
      properties:
        type:
          type: string
          description: Тип плательщика.
          enum:
          - INDIVIDUAL
          - LEGAL
          - NONE
          example: LEGAL
        name:
          type: string
          description: Наименование плательщика.
          example: ООО Покупатель
        inn:
          type: string
          description: ИНН плательщика.
          example: '394439302723'
        kpp:
          type: string
          description: КПП плательщика.
          example: '637996731'
        address:
          type: string
          description: Адрес плательщика.
          example: г. Москва, ул. Тестовая, д. 1
      required:
      - type
    GoodsRequest:
      type: object
      description: Товары
      example:
        items:
        - name: Услуги по настройке ПО
          count: 5
          price: 1200.5
          unit: HOUR
          vat: VAT_20
      properties:
        items:
          type: array
          description: Список товаров
          items:
            $ref: '#/components/schemas/ItemRequest'
          maxItems: 2147483647
          minItems: 1
          example:
          - name: Услуги по настройке ПО
            count: 5
            price: 1200.5
            unit: HOUR
            vat: VAT_20
      required:
      - items
    Payer:
      type: object
      description: Плательщик
      example:
        type: LEGAL
        name: ООО Покупатель
        inn: '394439302723'
        kpp: '637996731'
        address: г. Москва, ул. Тестовая, д. 1
      properties:
        type:
          type: string
          description: Тип плательщика. INDIVIDUAL (ФЛ) / LEGAL (юр. лицо) / NONE (без типа)
          enum:
          - INDIVIDUAL
          - LEGAL
          - NONE
          example: LEGAL
        name:
          type: string
          description: Наименование плательщика
          example: ООО Покупатель
        inn:
          type: string
          description: ИНН плательщика
          example: '394439302723'
        kpp:
          type: string
          description: КПП плательщика
          example: '637996731'
        address:
          type: string
          description: Адрес плательщика
          example: г. Москва, ул. Тестовая, д. 1
      required:
      - type
    PayeeResponse:
      type: object
      description: Получатель платежа
      example:
        inn: '394439302723'
        kpp: '637996731'
        cnum: UVGASK
        name: ООО Продавец
        juridicalAddress: 123154, Москва г, ул. Тестовая, д. 2
        lawType: ООО
        account:
          name: АО «Банк»
          num: '51421810026450470886'
          branchName: Московский филиал АО «Банк»
          corrAcc: '30101810400000000598'
          bic: 081395980
      properties:
        inn:
          type: string
          description: ИНН получателя платежа
          example: '394439302723'
        kpp:
          type: string
          description: КПП получателя платежа
          example: '637996731'
        cnum:
          type: string
          description: CNUM организации
          example: UVGASK
        name:
          type: string
          description: Наименование получателя платежа
          example: ООО Продавец
        juridicalAddress:
          type: string
          description: Юридический адрес получателя платежа
          example: 123154, Москва г, ул. Тестовая, д. 2
        lawType:
          type: string
          description: Организационно-правовая форма
          example: ООО
        account:
          $ref: '#/components/schemas/AccountResponse'
          description: Банковский счёт получателя платежа
      required:
      - account
      - cnum
      - inn
      - juridicalAddress
    BillPaymentResponse:
      type: object
      description: Оплата по счету
      properties:
        transactionKey:
          type: string
          description: Уникальный ключ транзакции для предотвращения дублей
          example: 2026-09-30_401900899873_123_6002.50
        operDate:
          type: string
          format: date
          description: Дата операции
          example: '2026-09-30'
        corrName:
          type: string
          description: Наименование контрагента
          example: ООО Покупатель
        total:
          type: number
          description: Сумма оплаты
          example: 6002.5
        docNum:
          type: string
          description: Номер документа
          example: '1'
        corrAccount:
          type: string
          description: Счёт контрагента
          example: '51421810026450470886'
        accountCurrency:
          type: string
          description: Валюта счета (код по ISO 4217)
          example: RUB
          enum:
          - AFA
          - ALK
          - ALL
          - DZD
          - ADP
          - AOK
          - AON
          - AZM
          - ARA
          - ARP
          - ARS
          - ARY
          - AUD
          - ATS
          - BSD
          - BHD
          - BDT
          - AMD
          - BBD
          - BEF
          - BMD
          - BTN
          - BOB
          - BOP
          - BAD
          - BWP
          - BRB
          - BRC
          - BRE
          - BRN
          - BZD
          - SBD
          - BND
          - BGJ
          - BGK
          - BGL
          - BUK
          - MMK
          - BIF
          - BYB
          - KHR
          - CAD
          - CVE
          - KYD
          - LKR
          - CLP
          - CNY
          - COP
          - KMF
          - ZRN
          - ZRZ
          - CRC
          - HRD
          - HRK
          - CUP
          - CYP
          - CSK
          - CSJ
          - CZK
          - DKK
          - DOP
          - ECS
          - SVC
          - GQE
          - ETB
          - ERN
          - EEK
          - FKP
          - FJD
          - FIM
          - FRF
          - DJF
          - GEK
          - GMD
          - DEM
          - DDM
          - GHC
          - GIP
          - GRD
          - GTQ
          - GNE
          - GNF
          - GNS
          - GYD
          - HTG
          - HNL
          - HKD
          - HUF
          - ISJ
          - ISK
          - INR
          - IDR
          - IRR
          - IQD
          - IEP
          - ILP
          - ILR
          - ILS
          - ITL
          - JMD
          - JPY
          - KZT
          - JOD
          - KES
          - KPW
          - KRW
          - KWD
          - KGS
          - LAJ
          - LAK
          - LBP
          - LSL
          - LSM
          - LVL
          - LVR
          - LRD
          - LYD
          - LTL
          - LTT
          - LUF
          - MOP
          - MGF
          - MWK
          - MYR
          - MVQ
          - MVR
          - MLF
          - MTL
          - MTP
          - MRO
          - MUR
          - MXN
          - MXP
          - MNT
          - MDL
          - MAD
          - MZE
          - MZM
          - OMR
          - NAD
          - NPR
          - NLG
          - ANG
          - AWG
          - VUV
          - NZD
          - NIC
          - NIO
          - NGN
          - NOK
          - PKR
          - PAB
          - PGK
          - PYG
          - PEH
          - PEI
          - PEN
          - PES
          - PHP
          - PLZ
          - PTE
          - GWE
          - GWP
          - TPE
          - QAR
          - ROK
          - ROL
          - RUB
          - RWF
          - SHP
          - STD
          - SAR
          - SCR
          - SLL
          - SGD
          - SKK
          - VNC
          - VND
          - SIT
          - SOS
          - ZAR
          - RHD
          - ZWC
          - ZWD
          - YDD
          - ESP
          - SSP
          - SDD
          - SDP
          - SRG
          - SZL
          - SEK
          - CHF
          - SYP
          - TJR
          - THB
          - TOP
          - TTD
          - AED
          - TND
          - TRL
          - TMM
          - UGS
          - UGW
          - UGX
          - UAK
          - MKD
          - RUR
          - SUR
          - EGP
          - GBP
          - TZS
          - USD
          - UYN
          - UYP
          - UYU
          - UZS
          - VEB
          - WST
          - YER
          - YUD
          - YUN
          - CSD
          - YUM
          - ZMK
          - TWD
          - SLE
          - VED
          - UYW
          - VES
          - MRU
          - STN
          - CUC
          - ZWL
          - BYN
          - TMT
          - ZWR
          - GHS
          - VEF
          - SDG
          - GHP
          - UYI
          - RSD
          - ZWN
          - MZN
          - AZN
          - AYM
          - RON
          - CHE
          - CHC
          - CHW
          - TRY
          - XAF
          - XCD
          - XOF
          - XPF
          - XEU
          - XBA
          - XBB
          - XBC
          - XBD
          - XAU
          - XDR
          - XAG
          - XPT
          - XTS
          - XPD
          - XUA
          - ZMW
          - SRD
          - MGA
          - COU
          - AFN
          - TJS
          - AOA
          - BYR
          - BGN
          - CDF
          - BAM
          - EUR
          - MXV
          - UAH
          - GEL
          - AOR
          - ECV
          - BOV
          - PLN
          - BRL
          - BRR
          - LUL
          - LUC
          - CLF
          - ZAL
          - BEL
          - BEC
          - XSU
          - ESB
          - ESA
          - USN
          - USS
          - XXX
        orgName:
          type: string
          description: Наименование организации
          example: ООО Продавец
        purpose:
          type: string
          description: Назначение платежа
          example: Оплата по счёту №1 от 30.09.2026
      required:
      - transactionKey
    DocNumberResponse:
      type: object
      description: Данные по номеру выставляемого счета
      properties:
        nextDocNumber:
          type: string
          description: Следующий доступный номер для выставляемого счета
          example: '12'
      required:
      - nextDocNumber
  parameters:
    IdTokenHeader:
      name: Id-Token
      in: header
      description: Идентификационный токен пользователя
      required: true
      schema:
        type: string
        format: byte
        example: SUQgVE9LRU4gRk9SIFRFU1RJTkc=
    AuthorizationHeader:
      name: Authorization
      in: header
      description: Токен доступа
      required: true
      schema:
        type: string
        format: byte
        example: Bearer QXV0aG9yaXphdGlvbiBIZWFkZXIgRm9yIFRlc3Rpbmc=
  examples:
    billDetailsResponse:
      summary: Детальная информация о счете на оплату
      value:
        id: 60612e6c-d182-4b59-a868-69714a910ee3
        status: PAYMENT_PENDING
        docNumber: '1'
        cnum: UVGASK
        goods:
          totalPrice: 6002.5
          totalVatAmount: 1000.42
          items:
          - id: 7c9e6679-7425-40de-944b-e07fc1f90ae7
            name: Услуги по настройке ПО
            count: 5
            price: 1200.5
            vat:
              name: VAT_20
              abbreviation: НДС 20%
              value: '20'
            unit:
              name: HOUR
              abbreviation: Часы
              value: ч
            sum: 6002.5
            vatAmount: 1000.42
        invoice:
          num: INV-2024-001
          date: '2026-09-30'
          cause: Оплата по договору №123456
          comment: Платёж по договору №123456
        payer:
          type: LEGAL
          name: ООО Покупатель
          inn: '394439302723'
          kpp: '637996731'
          address: г. Москва, ул. Тестовая, д. 1
        payee:
          inn: '394439302723'
          kpp: '637996731'
          cnum: UVGASK
          name: ООО Продавец
          juridicalAddress: 123154, Москва г, ул. Тестовая, д. 2
          lawType: ООО
          account:
            name: АО «Банк»
            num: '51421810026450470886'
            branchName: Московский филиал АО «Банк»
            corrAcc: '30101810400000000598'
            bic: 081395980
        linkedDocuments: []
        payments: []
        statusIsUpdating: false
        createdOn: '2026-09-30T10:19:26'
        receipts: []
    measurementResponse:
      summary: Список единиц измерения и ставок НДС
      value:
        vat:
        - name: VAT_0
          abbreviation: НДС 0%
          value: '0'
        - name: VAT_20
          abbreviation: НДС 20%
          value: '20'
        units:
        - name: PIECE
          abbreviation: Штуки
          value: шт
        - name: HOUR
          abbreviation: Часы
          value: ч
    billStatusUpdateRequest:
      summary: Запрос на обновление статуса счетов
      value:
        billIds:
        - 3fa85f64-5717-4562-b3fc-2c963f66afa6
        status: PAID
    billListResponse:
      summary: Список счетов на оплату
      value:
        totalElements: 1
        totalPages: 1
        first: true
        last: true
        statusIsUpdating: false
        numberOfElements: 1
        pageable:
          paged: true
          pageNumber: 0
          pageSize: 30
          unpaged: false
          offset: 0
          sort:
            sorted: true
            unsorted: false
            empty: false
        size: 30
        content:
        - id: 60612e6c-d182-4b59-a868-69714a910ee3
          cnum: UVGASK
          status: PAYMENT_PENDING
          createdDate: 1.790763566E9
          invoiceDate: 1.7907264E9
          docNumber: '1'
          payer:
            name: ООО Покупатель
            type: LEGAL
            inn: '394439302723'
            kpp: '637996731'
            address: г. Москва, ул. Тестовая, д. 1
          payee:
            name: ООО Продавец
            inn: '394439302723'
            kpp: '637996731'
            address: 123154, Москва г, ул. Тестовая, д. 2
          amount: 6002.5
          items:
          - id: 7c9e6679-7425-40de-944b-e07fc1f90ae7
            name: Услуги по настройке ПО
            count: 5
            price: 1200.5
            vat:
              name: VAT_20
              abbreviation: НДС 20%
              value: '20'
            unit:
              name: HOUR
              abbreviation: Часы
              value: ч
            sum: 6002.5
            vatAmount: 1000.42
          linkedDocuments: []
          numberOfRemainingLinkedDocuments: 0
          receipts: []
        number: 0
        sort:
          sorted: true
          unsorted: false
          empty: false
        empty: false
    billRequest:
      summary: Запрос на создание счета на оплату
      value:
        goods:
          items:
          - name: Услуги по настройке ПО
            count: 5
            price: 1200.5
            unit: HOUR
            vat: VAT_20
        invoice:
          num: INV-2024-001
          date: '2026-09-30'
          cause: Оплата по договору №123456
          comment: Платёж по договору №123456
        payer:
          type: LEGAL
          name: ООО Покупатель
          inn: '394439302723'
          kpp: '637996731'
          address: г. Москва, ул. Тестовая, д. 1
        payee:
          inn: '394439302723'
          kpp: '637996731'
          name: ООО Продавец
          lawType: ООО
          juridicalAddress: 123154, Москва г, ул. Тестовая, д. 2
          account:
            name: АО «Банк»
            num: '51421810026450470886'
            bic: 081395980
            branchName: Московский филиал АО «Банк»
            corrAcc: '30101810400000000598'
        closingDocuments: []
        receipts: []
    billUpdateRequest:
      summary: Запрос на обновление счета на оплату
      value:
        goods:
          items:
          - id: 3fa85f64-5717-4562-b3fc-2c963f66afa6
            name: Услуги по настройке ПО
            count: 5
            price: 1200.5
            unit: HOUR
            vat: VAT_20
        invoice:
          num: INV-2024-001
          date: '2026-09-30'
          cause: Оплата по договору №123456
          comment: Платёж по договору №123456
        payer:
          type: LEGAL
          name: ООО Покупатель
          inn: '394439302723'
          kpp: '637996731'
          address: г. Москва, ул. Тестовая, д. 1
        payee:
          inn: '394439302723'
          kpp: '637996731'
          name: ООО Продавец
          lawType: ООО
          juridicalAddress: 123154, Москва г, ул. Тестовая, д. 2
          account:
            name: АО «Банк»
            num: '51421810026450470886'
            bic: 081395980
            branchName: Московский филиал АО «Банк»
            corrAcc: '30101810400000000598'
        closingDocuments: []
    billResponse:
      summary: Ответ на создание счета на оплату
      value:
        documentId: 3fa85f64-5717-4562-b3fc-2c963f66afa6
  responses:
    Unauthorized:
      description: Аутентификация не пройдена
    InternalError:
      description: Внутренняя ошибка
